ValueError: missing values
One more attempt to resolve the following error: 'ValueError: oops! synthetic data contains missing values'. When it has a null value, replace it with zero.